In [87]:
%matplotlib inline
import pandas
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import normalize

In [88]:
data_url="http://goo.gl/vhm1eU"

In [89]:
names = ['prg', 'plas', 'pres','skin','test','mass','pedi', 'age','class']

df = pandas.read_csv(data_url, names=names)
df[:5]

prg  plas  pres  skin  test  mass   pedi  age  class
0    6   148    72    35     0  33.6  0.627   50      1
1    1    85    66    29     0  26.6  0.351   31      0
2    8   183    64     0     0  23.3  0.672   32      1
3    1    89    66    23    94  28.1  0.167   21      0
4    0   137    40    35   168  43.1  2.288   33      1

In [90]:
y_data=df['class']
#y_data=y_data.reshape(len(y_data),1)
y_data[:5]

0    1
1    0
2    1
3    0
4    1
Name: class, dtype: int64

In [91]:
x_data=df.ix[:,:-1]
norm_x= normalize(x_data, axis=0)
#norm_x=(x_data-x_data.min())/(x_data.max()-x_data.min())
norm_x[:5]

array([[ 0.04235974,  0.04270834,  0.03620428,  0.04857917,  0.        ,
         0.03679789,  0.03924821,  0.05117289],
       [ 0.00705996,  0.02452844,  0.03318725,  0.04025131,  0.        ,
         0.02913166,  0.02197149,  0.03172719],
       [ 0.05647966,  0.05280828,  0.03218158,  0.        ,  0.        ,
         0.02551759,  0.04206507,  0.03275065],
       [ 0.00705996,  0.02568272,  0.03318725,  0.03192345,  0.02420843,
         0.03077443,  0.01045367,  0.02149261],
       [ 0.        ,  0.03953407,  0.02011349,  0.04857917,  0.04326614,
         0.04720206,  0.14322153,  0.03377411]])

In [92]:
x_data=norm_x#.values
x1=np.ones(len(x_data))
x1=x1.reshape(len(x_data),1)
x_data=np.float32(np.concatenate((x1, x_data), axis=1))
x_data=np.transpose(x_data)
x_data[:5]

array([[ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 0.04235974,  0.00705996,  0.05647966, ...,  0.03529979,
         0.00705996,  0.00705996],
       [ 0.04270834,  0.02452844,  0.05280828, ...,  0.03491695,
         0.0363598 ,  0.026837  ],
       [ 0.03620427,  0.03318725,  0.03218158, ...,  0.03620427,
         0.03017023,  0.0351986 ],
       [ 0.04857917,  0.04025131,  0.        , ...,  0.03192345,
         0.        ,  0.04302726]], dtype=float32)

In [93]:
X=tf.placeholder(tf.float32)
Y=tf.placeholder(tf.float32)

W = tf.Variable(tf.random_uniform([1,len(x_data)], -1.0, 1.0))


In [94]:
h=tf.matmul(W,X)
hypothesis = tf.div(1., 1. + tf.exp(-h))
cost = -1 * tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y) * tf.log(1-hypothesis))

In [95]:
a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

init = tf.initialize_all_variables()

sess = tf.Session()
sess.run(init)

for step in range(10000000):
    sess.run(train, feed_dict={X: x_data, Y:y_data})
    if step % 100000 == 0:
        print (step, sess.run(cost, feed_dict={X: x_data, Y:y_data}),sess.run(W))
        

0 0.681257 [[-0.13065343 -0.57542157  0.82422173  0.53981543 -0.10025775 -0.69557816
   0.78039277 -0.77743769  0.66488403]]
100000 0.562532 [[ -2.77527499  12.79704857  17.16769981   1.27397776   2.13724399
    5.72657728  10.27228832   9.21959209   9.15509033]]
200000 0.538028 [[ -3.73734832  15.65484238  29.4863472    0.3961567    1.64876568
    5.2787137   17.62490273  12.56608772  12.82354259]]
300000 0.52273 [[ -4.36277962  15.96190357  39.70536423  -0.93416691   1.1896261
    4.28841782  23.88166237  13.82706547  14.76299763]]
400000 0.511698 [[ -4.83716536  15.71691704  48.39730453  -2.41151643   0.89355493
    3.34264684  29.31021309  14.2848444   15.90873718]]
500000 0.503415 [[ -5.2239337   15.43688869  55.90698242  -3.91355348   0.71604729
    2.50973153  34.0591507   14.42720795  16.60236168]]
600000 0.49708 [[ -5.55042505  15.24615383  62.42777252  -5.39312077   0.61293203
    1.78558946  38.25583649  14.44152546  17.03021049]]
700000 0.492173 [[ -5.83000135  15.13887215 

KeyboardInterrupt: 

In [122]:
w_list=sess.run(W)
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [124]:
x_data=np.transpose(x_data)
w_list=w_list.T
x_data.dot(w_list)[:5]


array([[ 0.6283251 ],
       [-2.3723309 ],
       [ 0.83715963],
       [-2.55067492],
       [ 1.61859512]], dtype=float32)

In [136]:
y_data=y_data.reshape(len(y_data),1)
sum((sigmoid(x_data.dot(w_list))>0.5) ==y_data)/y_data.shape[0]

array([ 0.76953125])