In [96]:
%matplotlib inline
import pandas
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import normalize

In [97]:
data_url="http://goo.gl/vhm1eU"

In [98]:
names = ['prg', 'plas', 'pres','skin','test','mass','pedi', 'age','class']

df = pandas.read_csv(data_url, names=names)
df[:5]

prg  plas  pres  skin  test  mass   pedi  age  class
0    6   148    72    35     0  33.6  0.627   50      1
1    1    85    66    29     0  26.6  0.351   31      0
2    8   183    64     0     0  23.3  0.672   32      1
3    1    89    66    23    94  28.1  0.167   21      0
4    0   137    40    35   168  43.1  2.288   33      1

In [99]:
y_data=df['class']
y_data=y_data.reshape(len(y_data),1)
y_data[:5]

array([[1],
       [0],
       [1],
       [0],
       [1]])

In [100]:
x_data=df.ix[:,:-1]
norm_x= normalize(x_data, axis=0)
#norm_x=(x_data-x_data.min())/(x_data.max()-x_data.min())
norm_x[:5]

array([[ 0.04235974,  0.04270834,  0.03620428,  0.04857917,  0.        ,
         0.03679789,  0.03924821,  0.05117289],
       [ 0.00705996,  0.02452844,  0.03318725,  0.04025131,  0.        ,
         0.02913166,  0.02197149,  0.03172719],
       [ 0.05647966,  0.05280828,  0.03218158,  0.        ,  0.        ,
         0.02551759,  0.04206507,  0.03275065],
       [ 0.00705996,  0.02568272,  0.03318725,  0.03192345,  0.02420843,
         0.03077443,  0.01045367,  0.02149261],
       [ 0.        ,  0.03953407,  0.02011349,  0.04857917,  0.04326614,
         0.04720206,  0.14322153,  0.03377411]])

In [101]:
x_data=norm_x#.values
x1=np.ones(len(x_data))
x1=x1.reshape(len(x_data),1)
x_data=np.float32(np.concatenate((x1, x_data), axis=1))
x_data=np.transpose(x_data)
x_data[:5]

array([[ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 0.04235974,  0.00705996,  0.05647966, ...,  0.03529979,
         0.00705996,  0.00705996],
       [ 0.04270834,  0.02452844,  0.05280828, ...,  0.03491695,
         0.0363598 ,  0.026837  ],
       [ 0.03620427,  0.03318725,  0.03218158, ...,  0.03620427,
         0.03017023,  0.0351986 ],
       [ 0.04857917,  0.04025131,  0.        , ...,  0.03192345,
         0.        ,  0.04302726]], dtype=float32)

In [102]:
X=tf.placeholder(tf.float32)
Y=tf.placeholder(tf.float32)

W = tf.Variable(tf.random_uniform([1,len(x_data)], -1.0, 1.0))


In [103]:
h=tf.matmul(W,X)
hypothesis = tf.div(1., 1. + tf.exp(-h))
cost = -1 * tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y) * tf.log(1-hypothesis))

In [104]:
a = tf.Variable(0.001)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

init = tf.initialize_all_variables()

sess = tf.Session()
sess.run(init)

for step in range(20000000):
    sess.run(train, feed_dict={X: x_data, Y:y_data})
    if step % 100 == 0:
        print (step, sess.run(cost, feed_dict={X: x_data, Y:y_data}),sess.run(W))
        

0 0.647583 [[-0.6829406  -0.69279969  0.44604933 -0.82880145  0.22054957  0.45860747
   0.34512296 -0.5092327  -0.02188428]]
100 0.647587 [[-0.68118238 -0.69274008  0.44610894 -0.82873863  0.2205947   0.45863307
   0.34518331 -0.50917906 -0.02182143]]
200 0.647532 [[-0.67946309 -0.6926856   0.44616854 -0.82867903  0.22063886  0.45865691
   0.34524292 -0.50912541 -0.02175989]]
300 0.647486 [[-0.67778176 -0.69263196  0.4462257  -0.82861942  0.22068207  0.45868075
   0.34530088 -0.50907177 -0.02169964]]
400 0.64746 [[-0.67613757 -0.69257832  0.44628233 -0.82855982  0.22072381  0.45870459
   0.34535751 -0.50901812 -0.02164066]]
500 0.647453 [[-0.67452973 -0.69252467  0.44633743 -0.82850021  0.2207647   0.4587267
   0.34541345 -0.50896996 -0.02158291]]
600 0.647413 [[-0.67295742 -0.69247103  0.44639108 -0.82844573  0.2208048   0.45874757
   0.34546709 -0.50892228 -0.02152637]]
700 0.647381 [[-0.67142004 -0.69241738  0.44644451 -0.82839209  0.22084354  0.45876843
   0.34552073 -0.5088746  -0

KeyboardInterrupt: 

In [105]:
w_list=sess.run(W)
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [106]:
x_data=np.transpose(x_data)
w_list=w_list.T
x_data.dot(w_list)[:5]
#sum((sigmoid(x_data.dot(w_list)) > 0.5) == y_data) / y_data.shape[0]

array([[-0.64126658],
       [-0.61837411],
       [-0.65866041],
       [-0.60224658],
       [-0.6299246 ]], dtype=float32)

In [107]:

sum((sigmoid(x_data.dot(w_list)) > 0.5) == y_data) / y_data.shape[0]

array([ 0.65104167])